In [1]:
from scipy.optimize import curve_fit
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics as st

In [2]:
df_stake_pdd_data = pd.read_csv(r'F:\North_Changri_Nup\Fitting\Stake_pdd_data.csv')
df_stake_pdd_data

,Stake Name,jd1,jd2,Debris Thickness,Time Period,Elevation,Obs_days,MB (cm w.e.),time_period,PDD
0,CNBL21−14,114,197,6.0,MB avr15_jul15,5471.842,83,97.25,2,106.899308
1,CNBL22−14,-29,113,33.0,MB nov14_avr15,5471.822,145,3.60,1,1.423643
2,CNBL22−14,114,197,33.0,MB avr15_jul15,5471.822,83,63.00,2,106.903023
3,CNBL22−14,198,229,33.0,MB jul15_aug15,5471.822,31,42.30,3,67.810478
4,CNBL23−14,-29,113,11.0,MB nov14_avr15,5471.604,145,3.60,1,1.425517
5,CNBL23−14,114,197,11.0,MB avr15_jul15,5471.604,83,79.20,2,106.943510
6,CNBL23−14,198,229,11.0,MB jul15_aug15,5471.604,31,54.90,3,67.834413
7,CNBL23−14,230,332,11.0,MB aug15_nov15,5471.604,102,60.30,4,83.520197
8,CNBL25−14,-29,113,13.5,MB nov14_avr15,5472.157,145,0.90,1,1.420764
9,CNBL25−14,114,197,13.5,MB avr15_jul15,5472.157,83,101.70,2,106.840806
10,CNBL25−14,198,229,13.5,MB jul15_aug15,5472.157,31,41.40,3,67.773752
11,CNBL25−14,230,332,13.5,MB aug15_nov15,5472.157,102,24.30,4,83.431882
12,CNBL26−14,114,197,41.0,MB avr15_jul15,5471.798,83,72.79,2,106.907480
13,CNBL26−14,230,332,41.0,MB aug15_nov15,5471.798,102,96.30,4,83.489215
14,CNBL27−14,-29,113,18.0,MB nov14_avr15,5471.506,145,0.90,1,1.426359
15,CNBL27−14,114,197,18.0,MB avr15_jul15,5471.506,83,107.10,2,106.961710
16,CNBL27−14,198,229,18.0,MB jul15_aug15,5471.506,31,9.00,3,67.845177
17,CNBL27−14,230,332,18.0,MB aug15_nov15,5471.506,102,41.40,4,83.535847
18,CNBL28−14,-29,113,13.0,MB nov14_avr15,5471.092,145,0.90,1,1.429917
19,CNBL28−14,114,197,13.0,MB avr15_jul15,5471.092,83,91.80,2,107.038640
20,CNBL28−14,198,229,13.0,MB jul15_aug15,5471.092,31,28.80,3,67.890693
21,CNBL28−14,230,332,13.0,MB aug15_nov15,5471.092,102,41.40,4,83.602029
22,CNBL29−14,114,197,1.0,MB avr15_jul15,5469.951,83,71.10,2,107.250774
23,CNBL29−14,198,229,1.0,MB jul15_aug15,5469.951,31,22.50,3,68.016235
24,CNBL29−14,230,332,1.0,MB aug15_nov15,5469.951,102,41.40,4,83.784441
25,CNBL30−14,114,197,20.0,MB avr15_jul15,5471.603,83,83.70,2,106.943695
26,CNBL30−14,198,229,20.0,MB jul15_aug15,5471.603,31,29.70,3,67.834522
27,CNBL30−14,230,332,20.0,MB aug15_nov15,5471.603,102,73.80,4,83.520356
28,CNBL33−14,-29,113,3.0,MB nov14_avr15,5470.223,145,3.71,1,1.437386
29,CNBL33−14,114,197,3.0,MB avr15_jul15,5470.223,83,197.89,2,107.200204
30,CNBL33−14,198,229,3.0,MB jul15_aug15,5470.223,31,128.70,3,67.986307

In [16]:
def func1(X, TF1, TF2):
    p, d = X
    return (TF1 * (d/100) ** TF2) * p / 10  # d is in cm, d/100 in meters

def func2(X, ddf, d0):
    p, d = X
    return ddf * p / (1 + (d / d0))/10   # divided by 10 to make it in cm, ddf is in mm/(day*C)

def func3(X, ddf, d0, a):
    p, d = X
    return ddf * p / ((1 + (d / d0) ** 2) ** a) / 10   # divided by 10 to make it in cm, ddf is in mm/(day*C)

p = df_stake_pdd_data['PDD']  # in C*day
d = df_stake_pdd_data['Debris Thickness']  # in cm
yData = df_stake_pdd_data['MB (cm w.e.)']  # in cm

initial_values1 = [0.5, -1]
popt1, pcov1 = curve_fit(func1, (p, d), yData, p0=np.asarray(initial_values1))  # fitting the data in the model1
print("Model1 : ", popt1, " Initial values ", initial_values1)

initial_values2 = [10, 60]
popt2, pcov2 = curve_fit(func2, (p, d), yData, p0=np.asarray(initial_values2))  # fitting the data in the model2
print("Model2 : ", popt2, " Initial values ", initial_values2)

initial_values3 = [10, 60, 5]
popt3, pcov3 = curve_fit(func3, (p, d), yData, p0=np.asarray(initial_values3))  # fitting the data in the model3
print("Model3 : ", popt3, " Initial values ", initial_values3)

ob_melt_rate = df_stake_pdd_data['MB (cm w.e.)']/df_stake_pdd_data.Obs_days
melt_model1 = (df_stake_pdd_data['PDD']* popt1[0] * (d/100) **df_stake_pdd_data['Debris Thickness'])/df_stake_pdd_data['Obs_days']/ 10
melt_model2 = (popt2[0]*df_stake_pdd_data['PDD']/(1 + df_stake_pdd_data['Debris Thickness']/popt2[1]))/df_stake_pdd_data['Obs_days']/10
melt_model3 = (popt3[0]*df_stake_pdd_data['PDD']/((1 + df_stake_pdd_data['Debris Thickness']/popt3[1])**2)**popt3[2])/df_stake_pdd_data['Obs_days']/10

#plt.scatter(melt_model2,ob_melt_rate )
rmse1 = (st.mean((ob_melt_rate - melt_model1)**2))**0.5
print('RMSE1 = ', rmse1, 'cm/day')
rmse2 = (st.mean((ob_melt_rate - melt_model2)**2))**0.5
print('RMSE2 = ', rmse2, 'cm/day')
rmse3 = (st.mean((ob_melt_rate - melt_model3)**2))**0.5
print('RMSE3 = ', rmse3, 'cm/day')

Model1 :  [ 6.84741631 -0.06573633]  Initial values  [0.5, -1]
Model2 :  [ 9.46025322 75.59502937]  Initial values  [10, 60]
Model3 :  [9.8468078  4.95966936 0.10651338]  Initial values  [10, 60, 5]
RMSE1 =  1.1932461733507274 cm/day
RMSE2 =  0.6232195549556369 cm/day
RMSE3 =  0.6138471482358716 cm/day